project:
  type: website
  output-dir: docs

website:
  title: "DataSciBC"
  search: false
  navbar:
    right:
      - href: index.qmd
        text: "Home"
      - href: onboarding.qmd
      - href: lab-charter.qmd
        text: "Charter"
      - href: people.qmd

format:
  html:
    theme: cosmo
    toc: true