project:
  type: website
  output-dir: docs

website:
  title: "DataSciBC"
  search: false
  favicon: assets/favicon.png
  navbar:
    right:
      - href: index.qmd
        text: "Home"
      - href: onboarding.qmd
      - href: lab-charter.qmd
        text: "Charter"
      - href: people.qmd
      # - href: journal-club.qmd
      #   text: "Journal Club"
      - icon: github # add icons as navbar buttons
        href: https://github.com/datascibc
        target: _blank
  page-footer:
    background: light # or `dark` or omit this option altogether (footer color will match page body color)
    left: Copyright 2026, DataSciBC
    right: This website is built with R and [Quarto](https://quarto.org/){target=_blank}

format:
  html:
    theme:
      - cosmo
      - custom.scss
    toc: true