---
title: "Onboarding"
format: html
---

Our on-boarding process is heavily inspired by [Kirstie Whittacre's](https://github.com/WhitakerLab/Onboarding) Lab group.
On-boarding aims to:

- Complete a minimum example of using git and github, by;
- Writing a short member profile.
- Investing some time in the lab group.

This process also serves to create a front end directory of lab members,
building our community over time.

In order to "on-board", please complete the following technical steps:

- [Install git](https://github.com/git-guides/install-git) on your local 
  machine.
- [Clone](https://github.com/git-guides/git-clone) a copy of this website 
  repo and create a new branch.
- Name the branch as `firstname-lastname` (e.g. `ed-palmer`)
- Add a profile page as a `.qmd` document in the `people` folder:
    - Use a category of "active lab member" in the yaml header of the file.
    - Take a look at any of the other profiles for examples.
- [Push](https://github.com/git-guides/git-push) your branch to github.
- Submit a pull request on github.

This will complete the technical aspects of on-boarding. You will have learnt
through this process, all the vital steps that we will be using for sharing code
and completing project peer review. If it feels daunting, please do not worry.
We are all here to help you with this process.

Beyond this, new members are expected to:

- Read and understand the lab charter, and follow our code of conduct.
- Contribute your knowledge and experience to others in the lab (as we will do
  with you.)

We look forward to seeing you in the lab!