---
title: "CAPE-COD"
author: "Ed Palmer"
draft: true
categories:
  - "respiratory"
---

## Background

The steroid evidence landscape in intensive care is complex. Really complex.
There are a number of conditions that may benefit from steroids including: septic shock, meningitis and ARDS.
The story in pneumonia is somewhat less clear.
A number of small RCTs---which were almost certainly underpowered---have been unable to detect a mortality benefit, which should not be a surprise.

There are strong reasons of biological plausibility, that severe bacterial
pneumonia would be susceptible to inflammatory modification with steroids.
However, there are rightly concerns about potential adverse sequelae of steroid use: overly aggressive immune suppression, hyperglycaemia, improper timing (i.e initiating too soon or too late).

## Trial Overview

This trial was a double blind, placebo controlled, French multi-centre RCT
conducted at 31 centres from 2015 to 2020. Randomisation took place in a 1:1
fashion with blocks across strata (center and use of mechanical ventilation).
1146 patients were needed to provide 80% power to detect a 25% relative risk
reduction in mortality from a baseline of 27%. This was rounded up to 1200 to
account for loss to follow up.

## PICO

- Population:
- Intervention: continuous infusion of hydrocortisone (200 mg / day)
- Comparator: matched placebo
- Outcomes:
    - Primary: 28 day mortality.
    - Secondary:

Recruitment was paused at 800 randomised patients; the planned second interim
analysis. This coincided with the COVID pandemic, and allowed this group to
pivot to investigating hydrocortisone in COVID-19, since the research apparatus was already established. After a long (and very understandable pause), the DSMB
recommended stopping trial because:

1) Based on available data, equipoise no
longer remained between groups
2) long term suspension of the trial would have
unknown impact on analysis
3) another 400 patients very unlikely to change
interpretation of results.

In context
| Study    | Steroid        | When? | Where?          | Why?             | How?
| Who? | | -------- | -------------- | ----- | --------------- |
---------------- | ---------------- | ---- | | CAPE-COD | Hydrocortisone | Early
| 31 ICUs, France | 28-day Mortality | Infusion + Taper | Sick | |          |
|       |                 |                  |                  |      |

## Results

The primary outcome, death from all causes by day 28 was 6.2% in the
hydrocortisone arm and 11.9% in the matched placebo arm. This corresponds to a
difference of -5.6% (-9.6% to -1.7%), p = 0.006 (chi square). There are a number
of secondary outcomes, which I include graphically below.

## Secondary Outcomes

- No significant difference in
    - Cumulative incidence of hospital acquired infection by day 28: 9.8 vs 11.1%
    - Cumulative incidence of GI bleeding by day 28: 2.2 vs 3.3%
- Significantly greater in intervention group
    - Median daily dose of insulin by day 7: 35.5 vs 20.0 IU/day
- Significantly less in intervention group
    - Death by day 90: 9.3% vs 14.7%
    - Cumulative incidence of endotracheal intubation by day 28: 18.0 vs 29.5%
    - Cumulative incidence of endotracheal intubation by day 28 in those not receiving at baseline: 19.5% vs 27.7%
    - Cumulative incidence of vasopressor initiation by day 28 in those not receiving at baseline: 15.3 vs 25.0%

# Subgroups of Interest

## Discussion

There are several important questions that arise from this trial. Rarely does a trial give us everything we want and this one is no different.
The severity criteria were already quite lax in my view, and I can't explain the
rationale to change the eligibility criteria part way through the trial. I'm not
so sure if this truly is a trial of "severe" pneumonia, but rather of pneumonia
with an oxygen requirement. Perhaps they are two in the same. Further, these
were not very sick patients. The SAPS II and SOFA scores demonstrate that these
patients were not very sick. Contrast with other steroid ICU trials. The
enrollment criteria were never going to produce a mortality of 25% and indeed, a
much lower control group mortality is exactly what we saw.
Further, all these patients were inside the ICU.

It's hard to translate this
directly into the UK which by comparison is a resource restricted environment.
Many of the patients in this trial would be managed on the ward in UK
environment. And so this begs the question, should we start steroids outside the
ICU in those eligible?

Although I view the point of admission to the ICU as a largely administrative
time point, it does create a different safety profile for the patient, some
positive, some negative. For those who think admission to the ICU is a slam dunk
positive intervention, I would invite them to read the ICE-CUB trial. Inside the ICU I can site
an art line, closely monitor both haemodynamic and gas exchange, and trivially
run a variable rate insulin infusion to control hyperglycaemia. This may offer a
favourable safety advantage in this context that I can't replicate on the ward.

An infusion of steroid, which may also necessitate an infusion of insulin, are
less realistic in a UK ward setting. In this context, I think a pragmatic use of QDS
hydrocortisone, is reasonable. But this requires buy in from parent teams who
will be looking after the patients outside ICU and will have to contend with the
inevitable hyperglycaemia.

Does this finding translate to patients who are not candidates for ICU? I would
say no. This is a fundamentally different patient population. Typically much
more frail, and susceptable to the adverse sequelae of steroids, particularly
outside the ICU. I don't think you can extrapolate that far from this
trial.

## Integrating with Other Major Trials

There are two major trials that interact with this one. First, DEXA-ARDS which
has several notable flaws. Most strikingly, the lack of appropriate blinding,
questions over the way in which allocation concealment was performed and the
lack of hyperglycaemia in the treatment arm. With further limitations from the
exclusion of patients with prior corticosteroid exposure. While I cannot ignore
the findings, and I would certainly administer dexamethasone to patients with
established ARDS, I would want another trial to be conducted that essentially
bridges these two trials. A properly blinded ARDS trial, where prior
steroid use wasn't an exclusion criteria. The question would then be, does...

The second is APROCHSS, which was a double blind randomised control trial
investigating the use of hydrocortisone plus fludrocortisone in established
septic shock. Briefly, patients in this trial were much sicker, with a minimum
noradrenaline requirement of 0.25, commensurate SAPS and SOFA scores, and a
control group mortality of xx. Although this was all comers with sepsis, the
single largest group would have been severe community acquired pneumonia.
Looking at the supplement xx. Again, this study excluded those who were exposed
to prior steroids.

There is now an abundance of data to show that steroids in septic shock speed
shock resolution, and likely improve mortality.

The third is HYPRESS which used steroids (hydrocortisone only)in sepsis in an
attempt to *prevent* the onset of shock.

REMAP-CAP steroids

Interaction with DNAR orders

## The Acid Test

My acid test for interpreting trial literature is whether or not you would want
the treatment for yourself or family members. I find it's a helpful heuristic to
follow and challenges us to bridge the gap between our intellectual side
(interpreting trial evidence in the cold) and our emotional side (where the
stakes are very high).

If I had a bacterial pneumonia, with an oxygen
requirement, I would want to receive steroids?

For me, the answer is yes.
And so I will be promoting the use of steroids in bacterial pneumonia with
an oxygen requirement in patients eligible for admission to the ICU.

## Wrapping Up

This trial showed that hydrocortisone improved mortality in a population of
patients with bacterial pneumonia (most commonly pneumococcus), who were being
treated inside an ICU, with an oxygen requirement, and in whom influenza had
been excluded. I would apply this to my practice by
I think equipoise remains to repeat this trial in the frail or elderly
population who are ineligible for treatment inside the ICU

## Recommendations

- Hydrocortisone should be administered to patients with severe CAP:
    - who meet inclusion criteria
    - Are being considered for admission to the ICU (i.e. can start before arrival, and continue in line with this protocol)
    - Where viral pneumonia has been excluded
- Pragmatically dose at 50 mg QDS
- Consider fludocortisone if patient develops septic shock.
- Switch to high dose dexamethasone if patient develops severe ARDS.
- Consider using regular procalcitonin in these patients, since we would lose the signal from white cells to monitor for secondary infective complications.